### PR TITLE
resolve security warning

### PR DESCRIPTION
**Pull request by Fuseteam**
this is an attempt to solve #132 without touching the hosts proxy config

### CODE REVIEW

**Comment by Fuseteam** [comment]
oh kay then service discovery cannot be done within the container the security warning however can
particularly this one: 
2021-05-05-151456_1190x45_scrot

**Comment by blizzz** [comment]
Sorry, that's also in the post install info:

> <h3>"Strict-Transport-Security" HTTP header</h3>

> To harden the service against man-in-the-middle attacks, this mechanism can be enabled. The SSL termination happens on the reverse proxy, which typically is an Apache2 web server on the host. The configuration for the domain(s) Nextcloud is running on would need to be extended with an HTTP header. Applying the changes affects all services running within this domain.

> This <a href="https://docs.nextcloud.com/server/20/admin_manual/installation/harden_server.html#enable-http-strict-transport-security">documentation page explains how to configure HSTS</a>. The <strong>includeSubDomains</strong> is necessary.

https://github.com/nextcloud/univention-app/blob/master/i18n/en/README_POST_INSTALL_EN

**Comment by Fuseteam** [comment]
but i tested it, and it worked, nextcloud no longer complained

**Comment by Fuseteam** [comment]
ok ok ok fine you win, i'm an idiot i should've read the comment in `/etc/apache2/sites-available/default-ssl.conf`
```
# Warning: This file is auto-generated and might be overwritten by
#          univention-config-registry.
#          Please edit the following file(s) instead:
# Warnung: Diese Datei wurde automatisch generiert und kann durch
#          univention-config-registry ueberschrieben werden.
#          Bitte bearbeiten Sie an Stelle dessen die folgende(n) Datei(en):
#
#       /etc/univention/templates/files/etc/apache2/sites-available/ssl.d/00start
#       /etc/univention/templates/files/etc/apache2/sites-available/ssl.d/10hsts
#       /etc/univention/templates/files/etc/apache2/sites-available/ssl.d/10univention-appcenter
#       /etc/univention/templates/files/etc/apache2/sites-available/ssl.d/99end
#
```
the proper solution via the commandline is

- set the proper redirects in `/etc/univention/templates/files/etc/apache2/sites-available/ssl.d/99end` by running
```
sed -i '1 i\Redirect 301 /.well-known/carddav /nextcloud/remote.php/dav\nRedirect 301 /.well-known/caldav /nextcloud/remote.php/dav' /etc/univention/templates/files/etc/apache2/sites-available/ssl.d/99end
```
- enable HSTS by running
```
ucr set apache2/hsts/max-age=15552000 apache2/hsts/includeSubDomains=yes apache2/hsts=yes
```
- ???
- profit

**Comment by blizzz** [comment]
thanks for the update :)

**Pull request closed without merging**
