### PR TITLE
chore(release): bump version to 26.0.10

### PR DESCRIPTION
**Pull request by juliusknorr**
- [x] test upgrade from 25.0.13
- [x] test new install 
- [x] tag new release
- [x] register release in the appcenter `univention-appcenter-control new-version 5.0/nextcloud 5.0/nextcloud=26.0.10-0`
- [x] Submit for approval  
- [x] review/merge

### CODE REVIEW

**Review by blizzz — APPROVED** [review]

**Comment by blizzz** [comment]
>  upload files to univention appcenter

NOOP: they fetch the docker images from github

**Comment by blizzz** [comment]
I used to tag the image and request publshing at UCS before merging. But it does not really make a difference, we can merge first.

**Comment by juliusknorr** [comment]
Did it in your order now

**Comment by blizzz** [comment]
Just FYI, the published version can also be seen at https://www.univention.com/products/app-catalog/nextcloud/. I used to double check after getting the confirmation. Then I also added release info to the tag, done here now: https://github.com/nextcloud/univention-app/releases/tag/26.0.10-0

**Pull request merged**
